=== MarkoKovacevic86/XML2016Projekat/XMLProject/src/schema/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:p="http://www.parlament.gov.rs/propisi/"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.parlament.gov.rs/propisi/" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    <xs:element name="Akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sporedni_deo">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="Akt_u_proceduri">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Predlagac" type="xs:string"/>
                                        <xs:element name="Upucuje_se" type="xs:string"/>
                                        <xs:element name="Meta_podaci">
                                            <xs:complexType>
                                                <xs:all>
                                                  <xs:element name="Oznaka" type="xs:string"/>
                                                  <xs:element name="Naziv" type="xs:string"/>
                                                  <xs:element name="Vrsta" type="xs:string"/>
                                                  <xs:element name="Datum" type="xs:date"/>
                                                  <xs:element name="Mesto" type="xs:string"/>
                                                  <xs:element name="Broj_glasova_za" type="xs:int"/>
                                                  <xs:element name="Broj_glasova" type="xs:int"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Donet_akt">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Donet_od_strane" type="xs:string"/>
                                        <xs:element name="Po_postupku" type="xs:string"/>
                                        <xs:element name="Po_cilju" type="xs:string"/>
                                        <xs:element name="Meta_podaci">
                                            <xs:complexType>
                                                <xs:all>
                                                  <xs:element name="Oznaka" type="xs:string"/>
                                                  <xs:element name="Naziv" type="xs:string"/>
                                                  <xs:element name="Vrsta" type="xs:string"/>
                                                  <xs:element name="Datum" type="xs:date"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="status" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glavni_deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Deo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="1" minOccurs="1" name="Sadrzaj">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="Glava">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Sadrzaj">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Clan"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Odeljak">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="Sadrzaj">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="unbounded" minOccurs="0"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="Odeljak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Sadrzaj">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Clan">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="Sadrzaj">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Stav"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Tacka"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="newAttribute"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="Clan">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Sadrzaj">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Stav"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Tacka"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="newAttribute"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Status">
                                <xs:complexType>
                                    <xs:all/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Glava">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Sadrzaj"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="newElement"/>
</xs:schema>

=== MarkoKovacevic86/XML2016Projekat/XMLProject/src/xml/akti/Akt8-u_proceduri.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Akt 
xmlns:p="http://www.parlament.gov.rs/propisi"
xmlns="http://www.w3.org/ns/rdfa#"
xmlns:pred="http://www.parlament.gov.rs/propisi/predicate/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.parlament.gov.rs/propisi ../../schema/akt.xsd ">
  <p:Glavni_deo/>
<p:Sporedni_deo about="http://www.parlament.gov.rs/propisi/akti/u_proceduri/doc8">
    <p:Akt_u_proceduri>
      <p:Predlagac>p:Predlagac</p:Predlagac>
      <p:Upucuje_se>p:Upucuje_se</p:Upucuje_se>
      <p:Meta_podaci>
        <p:Oznaka property="pred:oznaka" datatype="xs:string">doc8</p:Oznaka>
        <p:Mesto property="pred:mesto" datatype="xs:string">Novi Sad</p:Mesto>
        <p:Datum property="pred:datum" datatype="xs:date">2012-02-10</p:Datum>
        <p:Vrsta property="pred:vrsta" datatype="xs:string">Zakon</p:Vrsta>
        <p:Naziv property="pred:naziv" datatype="xs:string">Pop me smara jer ne ume da se igra sa pdf-om</p:Naziv>
        <p:BrUkupnihGlasova>0</p:BrUkupnihGlasova>
        <p:BrPozitivnihGlasova>0</p:BrPozitivnihGlasova>
      </p:Meta_podaci>
    </p:Akt_u_proceduri>
  </p:Sporedni_deo>
</p:Akt>

=== MarkoKovacevic86/XML2016Projekat/XMLProject/src/xml/akti/Akt1_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Akt 
xmlns:p="http://www.parlament.gov.rs/propisi/" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.parlament.gov.rs/propisi/ ../../schema/akt.xsd "  
status="donet">
  <p:Glavni_deo/>
  <p:Sporedni_deo>
   <p:Donet_akt>
      <p:Donet_od_strane>string</p:Donet_od_strane>
      <p:Po_postupku>string</p:Po_postupku>
      <p:Po_cilju>string</p:Po_cilju>
      <p:Meta_podaci>
        <p:Oznaka>doc1</p:Oznaka>
        <p:Datum>2017-10-29</p:Datum>
        <p:Vrsta>Odluka</p:Vrsta>
        <p:Naziv>Ja dono Akt</p:Naziv>
      </p:Meta_podaci>
      <p:Osnov_donosenja>string</p:Osnov_donosenja>
    </p:Donet_akt>
  </p:Sporedni_deo>
</p:Akt>

=== MarkoKovacevic86/XML2016Projekat/XMLProject/src/xml/akti/akt.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Akt xmlns:p="http://www.parlament.gov.rs/propisi/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.parlament.gov.rs/propisi/ ../../schema/akt.xsd ">
  <p:Glavni_deo/>
  <p:Sporedni_deo>
    <p:Akt_u_proceduri>
      <p:Predlagac>p:Predlagac</p:Predlagac>
      <p:Upucuje_se>p:Upucuje_se</p:Upucuje_se>
      <p:Meta_podaci>
        <p:Oznaka>p:Oznaka</p:Oznaka>
        <p:Mesto>p:Mesto</p:Mesto>
        <p:Datum>2001-01-01</p:Datum>
        <p:Vrsta>p:Vrsta</p:Vrsta>
        <p:Naziv>p:Naziv</p:Naziv>
        <p:BrUkupnihGlasova>0</p:BrUkupnihGlasova>
        <p:BrPozitivnihGlasova>0</p:BrPozitivnihGlasova>
      </p:Meta_podaci>
    </p:Akt_u_proceduri>
  </p:Sporedni_deo>
</p:Akt>
